### ISSUE TITLE
Cannot assign a value to final variable and 'structureConfig' has private access.

### ISSUE THREAD

**Issue by BitbanChou** [TelepathicGrunt/StructureTutorialMod#13]
Hi，there.
I copy your code in my program and find some problem that I cant solve.Could you please help me?
In STStructures.java file：
![image](https://user-images.githubusercontent.com/59107518/135826976-e64fccf7-e2d1-419c-b0a6-3a9b30cfe55a.png)
![image](https://user-images.githubusercontent.com/59107518/135827421-7b7d9f04-9196-46ca-9ce4-ba576dcc09d7.png)
![image](https://user-images.githubusercontent.com/59107518/135827135-ff22d896-472a-49be-bb2f-7c78a90d36be.png)

**Comment by TelepathicGrunt** [comment]
Hello, if you read the above comments, they will tell you that you need to use accesstransformer to make these fields accessible and be able to be assigned a value.

Here’s the instructions I left in the readme about accesstransformers:


`When making your own mod, make sure to include the accesstransformer file and to include it in your build.gradle. If your IDE still say that the methods listed in the access transformer are private and shows an error, then you may need to refresh gradle and generate the runs again so the accesstransformers takes effect.
`

And here’s the accesstransformer file that is need (it has to be at this spot in your project)
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/1.16.3-Forge-jigsaw/src/main/resources/META-INF/accesstransformer.cfg

And lastly, make sure your build.gradle file has the accesstransformer line uncommented out so that refreshing gradle will now know to read the file for what fields to change the accessibility of
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/e51cca9698110559f8f586b9c71ae9a4e655d786/build.gradle#L30

I hope this is clear!

**Comment by BitbanChou** [comment]
thanks so much,the problem has solved now.

**Comment by TelepathicGrunt** [comment]
No problem! I'll close this report now
