### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by NationPlayz65** [TelepathicGrunt/StructureTutorialMod#28]
I don't know if I'm stupid or missing something for the structure to naturally generate, i can use the /place structure command but when i try to locate my structure it comes with 2 random things

#c:hidden_from_displayers
And
#c:hidden_from_locator_selection

**Comment by TelepathicGrunt** [comment]
The tags are only for other mods locator stuff such as structure compass and stuff.

I would need to see your entire setup and minecraft version to help. Did you make sure to add a structure set file that uses the structure? And the structure file is given a biome tag that you made too?

**Comment by NationPlayz65** [comment]
I don't exactly know how to give you my entire setup since I'm quite new to GitHub

But other than that I'm using Fabric 1.21.1
And yes to both

**Comment by TelepathicGrunt** [comment]
There’s a few videos online that can show you how to use GitHub Desktop to make a new repository and upload your project to it to share it more easily. Zipping it up and sending the project to me that way could also work. This is one of those things that’s easier to debug with it opened in front of me than guessing here. Only thing I can think of if no typos or anything is clear your IDE’s cache in case it is not loading the json files

**Comment by NationPlayz65** [comment]
I've decided to just zip the project and send it to you since i had some problems on trying to make a repository, where do i send it to you?

**Comment by TelepathicGrunt** [comment]
Here. Can drop in zip file. If too large, public link using Dropbox or Google drive also works

**Comment by NationPlayz65** [comment]
https://drive.google.com/drive/folders/1Vw7yZxSBQqdamJoC2P2-dbdnYpTTc4gB?usp=sharing

heres the google drive link since the file was too big

**Comment by TelepathicGrunt** [comment]
Opened up your mod. First thing I see is `structures` folder.
![image](https://github.com/user-attachments/assets/2df67f0c-a778-4d56-a428-471ee3b06e02)

This should be `structure`. Mojang depluralized several folders in 1.21.x. 

Second issue is this is a Nether spawning structure. And your structure json file has a project to heightmap line. This will iterate from top down to the first solid block. In the nether, what is the top solid block? The nether rooftop. 
![image](https://github.com/user-attachments/assets/d77f086a-486e-43c4-8119-6a2eb8c3db06)

Remove `project_start_to_heightmap` and set start height to absolute 40 so it spawns the structure at y = 40 in nether so you can verify that it spawns.

Once you do that and looks good, you are going to need to make a new structure type class, register it, and change `"type": "minecraft:jigsaw",` to use the new class. In the class, you would have it scan for surface of a ledge to spawn the house on instead of a fixed height.

Example custom structure type:
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/1.21-Fabric-Jigsaw/src/main/java/com/telepathicgrunt/structure_tutorial/structures/SkyStructures.java

Registering:
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/4d5b4b841170e08962754cff8f09ec5e57cd0858/src/main/java/com/telepathicgrunt/structure_tutorial/STStructures.java#L21

Usage in json file:
https://github.com/TelepathicGrunt/StructureTutorialMod/blob/4d5b4b841170e08962754cff8f09ec5e57cd0858/src/main/resources/data/structure_tutorial/worldgen/structure/code_structure_sky_fan.json#L6

Code I personally use to look for topmost or bottommost ledge surface to spawn my structures on in nether. This is using Mojmap mappings so you'll need to convert it to yarn if you're using yarn
https://github.com/TelepathicGrunt/RepurposedStructures/blob/0aac1367f6f3c1d220e02bd4aa4c982f21368433/common/src/main/java/com/telepathicgrunt/repurposedstructures/utils/GeneralUtils.java#L157-L196

**Comment by NationPlayz65** [comment]
Well how do i get started on converting the code to yarn? I'm using yarn and i have no clue where to actually start

**Comment by TelepathicGrunt** [comment]
The structure tutorial mod’s fabric branch is yarn already. The repurposed structures code is mojmap. Can use this https://linkie.shedaniel.dev/mappings?namespace=mojang_raw&version=1.20.6&search=Structure&translateMode=ns&translateAs=yarn

**Comment by NationPlayz65** [comment]
Thanks for the help! Everything works great, I know now how to actually spawn structures without it breaking on me now lol
